import type {
  AvailabilitySource,
  CatalogSource,
  Offer,
  Title,
} from "./domain.ts";

// Real title names; original summaries. Offers and safety annotations are illustrative
// fixtures, not a current catalog or an authoritative content advisory.
export const TITLES: Title[] = [
  {
    id: "moana",
    name: "Moana",
    year: 2016,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Animation", "Adventure"],
    summary:
      "A young navigator crosses the ocean on a journey to help her island and discover who she wants to be.",
    duration: "1h 47m",
    providerIds: ["disney"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "ocean",
    palette: ["#0b7c90", "#ffbc86"],
  },
  {
    id: "encanto",
    name: "Encanto",
    year: 2021,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Animation", "Musical"],
    summary:
      "In a family full of extraordinary gifts, one ordinary girl may hold the answer to saving their magical home.",
    duration: "1h 42m",
    providerIds: ["disney"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "garden",
    palette: ["#855b9e", "#f5b26c"],
  },
  {
    id: "mandalorian",
    name: "The Mandalorian",
    year: 2019,
    kind: "Series",
    rating: "TV-14",
    ageLevel: 2,
    genres: ["Science fiction", "Adventure"],
    summary:
      "A lone bounty hunter finds an unexpected responsibility while traveling through the outer reaches of the galaxy.",
    duration: "Series",
    providerIds: ["disney"],
    topics: ["violence"],
    seasonal: [],
    artworkRisk: "disturbing",
    art: "space",
    palette: ["#486c79", "#dfaa75"],
  },
  {
    id: "hocus-pocus",
    name: "Hocus Pocus",
    year: 1993,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Fantasy", "Comedy"],
    summary:
      "Three witches return to a New England town, leaving a group of young friends to put an end to their mischief.",
    duration: "1h 36m",
    providerIds: ["disney"],
    topics: ["scary"],
    seasonal: ["halloween"],
    artworkRisk: "seasonal",
    art: "moon",
    palette: ["#624b92", "#e3a870"],
  },
  {
    id: "coco",
    name: "Coco",
    year: 2017,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Animation", "Music"],
    summary:
      "A young musician follows a family mystery into an extraordinary world of memory, music, and connection.",
    duration: "1h 45m",
    providerIds: ["disney"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "garden",
    palette: ["#69479f", "#fb9a5b"],
  },
  {
    id: "only-murders",
    name: "Only Murders in the Building",
    year: 2021,
    kind: "Series",
    rating: "TV-MA",
    ageLevel: 3,
    genres: ["Comedy", "Mystery"],
    summary:
      "Three neighbors turn their shared enthusiasm for true crime into an investigation much closer to home.",
    duration: "Series",
    providerIds: ["hulu"],
    topics: ["violence", "language"],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#965844", "#ecc983"],
  },
  {
    id: "abbott",
    name: "Abbott Elementary",
    year: 2021,
    kind: "Series",
    rating: "TV-PG",
    ageLevel: 1,
    genres: ["Comedy"],
    summary:
      "Dedicated teachers navigate the everyday surprises of a Philadelphia public school with humor and heart.",
    duration: "Series",
    providerIds: ["hulu"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#587568", "#eaba72"],
  },
  {
    id: "the-bear",
    name: "The Bear",
    year: 2022,
    kind: "Series",
    rating: "TV-MA",
    ageLevel: 3,
    genres: ["Drama", "Comedy"],
    summary:
      "A chef returns to Chicago to run a family restaurant, where relationships can be as intense as the kitchen.",
    duration: "Series",
    providerIds: ["hulu"],
    topics: ["language"],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#3e6480", "#c6a374"],
  },
  {
    id: "prey",
    name: "Prey",
    year: 2022,
    kind: "Movie",
    rating: "R",
    ageLevel: 3,
    genres: ["Action", "Horror"],
    summary:
      "A resourceful Comanche hunter faces a dangerous visitor while protecting the people and land she knows.",
    duration: "1h 40m",
    providerIds: ["hulu"],
    topics: ["horror", "violence"],
    seasonal: [],
    artworkRisk: "disturbing",
    art: "forest",
    palette: ["#315e63", "#b4b479"],
  },
  {
    id: "mitchells",
    name: "The Mitchells vs. the Machines",
    year: 2021,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Animation", "Comedy"],
    summary:
      "An eccentric family road trip becomes a rescue mission when everyday technology turns against humanity.",
    duration: "1h 54m",
    providerIds: ["netflix"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#a1447e", "#f8b46b"],
  },
  {
    id: "wednesday",
    name: "Wednesday",
    year: 2022,
    kind: "Series",
    rating: "TV-14",
    ageLevel: 2,
    genres: ["Mystery", "Fantasy"],
    summary:
      "A sharp-minded student investigates a mystery at her unusual boarding school while learning about her family.",
    duration: "Series",
    providerIds: ["netflix"],
    topics: ["scary", "violence"],
    seasonal: [],
    artworkRisk: "disturbing",
    art: "moon",
    palette: ["#514a81", "#a3a1cc"],
  },
  {
    id: "stranger-things",
    name: "Stranger Things",
    year: 2016,
    kind: "Series",
    rating: "TV-14",
    ageLevel: 2,
    genres: ["Science fiction", "Horror"],
    summary:
      "Friends in a small town uncover a secret experiment and a parallel world after one of their own disappears.",
    duration: "Series",
    providerIds: ["netflix"],
    topics: ["horror", "violence", "language"],
    seasonal: [],
    artworkRisk: "disturbing",
    art: "forest",
    palette: ["#884252", "#ca8d86"],
  },
  {
    id: "our-planet",
    name: "Our Planet",
    year: 2019,
    kind: "Series",
    rating: "TV-PG",
    ageLevel: 1,
    genres: ["Documentary", "Nature"],
    summary:
      "Explore the landscapes and wildlife of our planet, and the connections that sustain its remarkable ecosystems.",
    duration: "Series",
    providerIds: ["netflix"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "mountain",
    palette: ["#44817f", "#b2d0a8"],
  },
  {
    id: "fellowship",
    name: "The Fellowship of the Ring",
    year: 2001,
    kind: "Movie",
    rating: "PG-13",
    ageLevel: 2,
    genres: ["Fantasy", "Adventure"],
    summary:
      "An unlikely fellowship begins a perilous journey to keep a powerful ring out of the hands of its creator.",
    duration: "2h 58m",
    providerIds: ["prime"],
    topics: ["violence"],
    seasonal: [],
    artworkRisk: "neutral",
    art: "mountain",
    palette: ["#627751", "#e0c88c"],
  },
  {
    id: "maisel",
    name: "The Marvelous Mrs. Maisel",
    year: 2017,
    kind: "Series",
    rating: "TV-MA",
    ageLevel: 3,
    genres: ["Comedy", "Drama"],
    summary:
      "A New York woman discovers a talent for stand-up comedy and begins a career that reshapes her life.",
    duration: "Series",
    providerIds: ["prime"],
    topics: ["language", "sexual"],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#9b5c79", "#e9b89f"],
  },
  {
    id: "the-boys",
    name: "The Boys",
    year: 2019,
    kind: "Series",
    rating: "TV-MA",
    ageLevel: 3,
    genres: ["Action", "Satire"],
    summary:
      "A determined group challenges celebrities with superpowers and the corporation that manages their public image.",
    duration: "Series",
    providerIds: ["prime"],
    topics: ["violence", "sexual", "language"],
    seasonal: [],
    artworkRisk: "disturbing",
    art: "city",
    palette: ["#477778", "#d9b67c"],
  },
  {
    id: "the-holiday",
    name: "The Holiday",
    year: 2006,
    kind: "Movie",
    rating: "PG-13",
    ageLevel: 2,
    genres: ["Romance", "Comedy"],
    summary:
      "Two women exchange homes across the Atlantic and find a change of scenery may bring unexpected connections.",
    duration: "2h 16m",
    providerIds: ["prime"],
    topics: ["language"],
    seasonal: ["christmas"],
    artworkRisk: "seasonal",
    art: "mountain",
    palette: ["#57748b", "#d6c4a7"],
  },
  {
    id: "spongebob",
    name: "SpongeBob SquarePants",
    year: 1999,
    kind: "Series",
    rating: "TV-Y7",
    ageLevel: 1,
    genres: ["Animation", "Comedy"],
    summary:
      "An optimistic fry cook and his underwater neighbors turn the ordinary days of Bikini Bottom into adventures.",
    duration: "Series",
    providerIds: ["paramount"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "ocean",
    palette: ["#208491", "#e6c45f"],
  },
  {
    id: "strange-new-worlds",
    name: "Star Trek: Strange New Worlds",
    year: 2022,
    kind: "Series",
    rating: "TV-14",
    ageLevel: 2,
    genres: ["Science fiction", "Adventure"],
    summary:
      "Captain Pike and the Enterprise crew explore new worlds while facing difficult choices far from home.",
    duration: "Series",
    providerIds: ["paramount"],
    topics: ["scary", "violence"],
    seasonal: [],
    artworkRisk: "unknown",
    art: "space",
    palette: ["#456886", "#d2ad77"],
  },
  {
    id: "mutant-mayhem",
    name: "Teenage Mutant Ninja Turtles: Mutant Mayhem",
    year: 2023,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Animation", "Action"],
    summary:
      "Four teenage turtle brothers venture into New York hoping to make friends and find their place in the city.",
    duration: "1h 39m",
    providerIds: ["paramount"],
    topics: ["violence"],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#49866b", "#cbb776"],
  },
  {
    id: "spongebob-movie",
    name: "The SpongeBob SquarePants Movie",
    year: 2004,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Animation", "Adventure"],
    summary:
      "SpongeBob and Patrick leave their familiar home on a sea-spanning quest to recover a stolen crown.",
    duration: "1h 27m",
    providerIds: ["paramount"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "ocean",
    palette: ["#317a9e", "#deb979"],
  },
  {
    id: "scream-vi",
    name: "Scream VI",
    year: 2023,
    kind: "Movie",
    rating: "R",
    ageLevel: 3,
    genres: ["Horror", "Mystery"],
    summary:
      "Survivors hoping to begin again in New York find that a familiar masked threat has followed them.",
    duration: "2h 2m",
    providerIds: ["paramount"],
    topics: ["horror", "violence", "language"],
    seasonal: [],
    artworkRisk: "disturbing",
    art: "moon",
    palette: ["#5e596d", "#ba9995"],
  },
  {
    id: "parks-and-rec",
    name: "Parks and Recreation",
    year: 2009,
    kind: "Series",
    rating: "TV-PG",
    ageLevel: 1,
    genres: ["Comedy"],
    summary:
      "An enthusiastic public servant and her colleagues tackle local government, friendships, and a long list of ambitious projects.",
    duration: "Series",
    providerIds: ["peacock"],
    topics: ["sexual", "language"],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#5a7f70", "#d1bd8c"],
  },
  {
    id: "despicable-me-2",
    name: "Despicable Me 2",
    year: 2013,
    kind: "Movie",
    rating: "PG",
    ageLevel: 1,
    genres: ["Animation", "Comedy"],
    summary:
      "A former supervillain balancing family life joins an unexpected partner to investigate a new threat.",
    duration: "1h 38m",
    providerIds: ["peacock"],
    topics: [],
    seasonal: [],
    artworkRisk: "neutral",
    art: "city",
    palette: ["#5888a0", "#e7c575"],
  },
];

export class PrototypeCatalog implements CatalogSource {
  async list(): Promise<Title[]> {
    return structuredClone(TITLES);
  }
}
export class PrototypeAvailability implements AvailabilitySource {
  async offersFor(titleId: string): Promise<Offer[]> {
    return (
      TITLES.find((title) => title.id === titleId)?.providerIds ?? []
    ).map((providerId) => ({
      titleId,
      providerId,
      region: "US",
      access: "subscription",
      provenance: "prototype",
    }));
  }
}
